version: 2.1
executors:
  base:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/spatialcurrent/go-adaptive-functions
jobs:
  pre_deps_golang:
    executor: base
    steps:
      - checkout
      - run: make deps_go
      - run: sudo chown -R circleci /go/src
      - save_cache:
          key: v1-go-src-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src
  test_go:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: make deps_go_test
      - run: make test_go
      - run: make imports
      - run: git diff --exit-code
  test_javascript:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: make deps_gopherjs
      - run: make deps_javascript
      - run: npm run test:clean
  examples:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: make deps_gopherjs
      - run: make deps_javascript
      - run: npm run test:clean
      - run: make run_example_javascript
  build_javascript:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: make deps_gopherjs
      - run: make build_javascript
      - store_artifacts:
          path: dist
          destination: /
workflows:
  main:
    jobs:
      - pre_deps_golang
      - test_go:
          requires:
            - pre_deps_golang
      - test_javascript:
          requires:
            - pre_deps_golang
      - examples:
          requires:
            - pre_deps_golang
      - build_javascript:
          requires:
            - pre_deps_golang
